### ISSUE TITLE
Unable to use hairpin

### ISSUE THREAD

**Issue by kaincenteno** [LandSandBoat/xiloader#10]
when trying to use hairpin, i get the following:

--hairpin: expected 0 argument(s). 1 provided.

Not passing anything after hairpin (that is not the --server argument)

**Comment by WinterSolstice8** [comment]
> I get the same issue when trying to use --hide.

Please try this new build: https://github.com/LandSandBoat/xiloader/releases/tag/v1.0.11

**Comment by Hokuten85** [comment]
> Please try this new build: https://github.com/LandSandBoat/xiloader/releases/tag/v1.0.11

Still have the same issue. --hide crashes the loader.

**Comment by claywar** [comment]
The original issue involves hairpin.  If hide is the issue now, we should probably track this separately.

**Comment by Hokuten85** [comment]
Looks like I may have goofed the testing up earlier. I just tried --hairpin and that worked. Went back and tried --hide and that also worked.  Not sure what happened, but it actually looks like both scenarios are good.
