### ISSUE TITLE
password changing can crash the lobby server

### ISSUE THREAD

**Issue by TeoTwawki** [LandSandBoat/xiloader#14]
Password changing can sometimes crash the lobby server by causing the watchdog to trip - a simple password change in a test database with only 6 player accounts hung up the map for more than 5000ms (I extended the watchdog time to see how long it'd go). That's an awfully long time for so simple a maneuver. When I tripped this, I was the only one on and had freshly started the exe's 15 min prior. I was able to repro it 5 of 7 tries. Crash dump available if desired.

Servers can work around this for the moment by disabling the watchdog (and their login will lag momentarily after someone resets a password).

**Comment by zach2good** [comment]
Hopefully this'll get fixed with: https://github.com/LandSandBoat/xiloader/pull/7 and https://github.com/LandSandBoat/server/pull/3049

**Comment by WinterSolstice8** [comment]
Seems to test fine when I change with the login rewrite. Not sure why it would be any different though, the sql et al is all the same.

**Comment by zach2good** [comment]
Is this still valid?

**Comment by TeoTwawki** [comment]
its fixed but I forgot the issue existed to close it, since it doesn't hit my notifications like the other repo's do and https://github.com/LandSandBoat/server/pull/3049 auto close it (because one repo can't close another issues as far as I know, even if linked)

**Comment by TeoTwawki** [comment]
well, dammit. just found a completely different related bug when double checking it before I hit close.
