### ISSUE TITLE
autologin activated showing when not being used

### ISSUE THREAD

**Issue by kaincenteno** [LandSandBoat/xiloader#15]
![image](https://github.com/LandSandBoat/xiloader/assets/26943220/30f86f76-ee15-4328-a8f2-cc8cf2aedb72)

getting "autologin activated" when not passing username + password as params of command

**Comment by Aomrep** [comment]
Did you ever figure this out? I'm having this exact issue now and can't figure it out.

**Comment by Moffet-1984** [comment]
Same here. I am having the same error.
