### ISSUE TITLE
Crash when using `--lang` option

### ISSUE THREAD

**Issue by RubenatorX** [LandSandBoat/xiloader#17]
I've looked at the code and haven't seen any obvious cause but, something about the latest changes makes xiloader totally crash when you use the `--lang` flag (e.g. `--lang US`).
Including this flag has been part of Windower's setup instructions so, fixing this would help a lot of people. Thanks.

Edit: I should specify, it crashes after login but before the game client launches.

**Comment by RubenatorX** [comment]
Did some more testing, seems to work fine standalone, but crashes when passed via Windower. This used to work fine though so, further investigation would be helpful.

**Comment by RubenatorX** [comment]
Update:
I attached a debugger... [this line](https://github.com/LandSandBoat/xiloader/blob/30a44efe38a4d2f3d2095e8263a6828bd28c85e7/src/main.cpp#L391) is spitting out
`Duplicate argument`

**Comment by WinterSolstice8** [comment]
check argv/argc with the debugger, is it actually there twice?

**Comment by RubenatorX** [comment]
Looks like yeah.
![image](https://github.com/LandSandBoat/xiloader/assets/5944121/6881f3d6-c9e2-4b46-91ba-e01e5a3b9c95)
I am still finding out if Windower always did that and using `--lang {region}` never actually did anything, but that's been in our instructions for a long time.

That aside, I suspect that possibly whatever repo/version/etc xiloader used to use as a dependency, possibly defaulted to allowing duplicate optional arguments, and that the new setup defaults to not allowing that.

**Comment by WinterSolstice8** [comment]
Interesting. This looks like "not an error" because it's correctly reporting you are doing something wrong, but maybe there's a way to tell argparse to use the last arg in the arguments as the newest one to preserve compatability

**Comment by WinterSolstice8** [comment]
If you change this line from
https://github.com/LandSandBoat/xiloader/blob/30a44efe38a4d2f3d2095e8263a6828bd28c85e7/src/main.cpp#L375

to
```args.add_argument("--lang").help("(optional) The language of your FFXI install: JP/US/EU (0/1/2).").append();```
does it work?

**Comment by zach2good** [comment]
New version available: https://github.com/LandSandBoat/xiloader/releases/tag/v1.1.1

**Comment by RubenatorX** [comment]
I had to sleep but, looks like there has been some incorrect/misleading instructions on our end for years. We definitely should not be passing in the same arg twice, so that is an accident, but the older xiloader definitely accepted the last argument and did not close.
We shall fix our instructions, but this change will help out all the people that followed the misleading instructions for years. Thank you!
