### ISSUE TITLE
Ashita just crashes on launch

### ISSUE THREAD

**Issue by Manpigg** [LandSandBoat/xiloader#23]
To my knowledge everything was set up according to the directions.  When i launch Ashita and i have account credentials entered in the .ini , it just crashes straight away.

**Comment by zach2good** [comment]
If you're having a crash, do you have a stacktrace or the logs from the crash? What comes up during the crash?

Or does something open and close very quickly?

Make sure you're following the instructions _exactly_: https://github.com/LandSandBoat/server/wiki/Client-Setup-Windows#ashita-v4

I launch from a Windows shortcut as part of my regular workflow and it works fine.

**Comment by Manpigg** [comment]
The launcher just open's and closes real quick. I tried to get a screenshot of the window, but it opens and closes to quick.  I have the shortcut setup for the launch as well.  i was following the quickstart guide, and Criticals video that she done.  i proably missed something but i cant find where i did.  

> If you're having a crash, do you have a stacktrace or the logs from the crash? What comes up during the crash?
> 
> Or does something open and close very quickly?
> 
> Make sure you're following the instructions _exactly_: https://github.com/LandSandBoat/server/wiki/Client-Setup-Windows#ashita-v4
> 
> I launch from a Windows shortcut as part of my regular workflow and it works fine.

  It just opens and closes really quick.  when i started this build, i had the quickstart guide i followed and Criticals video that she done.  I dont think i missed anything and ive gone back n forth on the video and guide, i cant seem to pick up what i missed.

I tried to get screenshot of launcher, but it opens and closes to quick.

if i dont have my username and password entered in the .ini file, it will keep the launcher open for the prompts to make account or login.  but at that point it doesnt really do anything, just keeps saying failed to login.

When i have the info entered in the .ini  (127.0.0.1 --Username -- Password )  it just opens and closes real quick.

**Comment by zach2good** [comment]
I can't vouch for whatever instructional videos exist elsewhere, but I'm 99% sure the LSB guides are all up to date.

I'm not sure if the arguments in the ini (that are directly passed to xiloader) are case-sensitive or not, be careful about that.
https://github.com/LandSandBoat/xiloader/blob/main/src/main.cpp#L365

Here's a breakdown of exactly my local setup, where I double click my shortcut and it launches the client (if the account doesn't exist because I've wiped my db it'll catch on the main xiloader screen and I can create the account at that point):
```
Replaced C:\ffxi\Ashita-v4beta\bootloader\pol.exe with the newest xiloader, and renamed to pol.exe
```

`C:\ffxi\Ashita-v4beta\config\boot\localhost_1.ini`
```
[ashita.boot]
; Private Server Usage
file        = .\\bootloader\\pol.exe
command     = --server 127.0.0.1 --user admin1 --pass admin1
gamemodule  = ffximain.dll
script      = default.txt
args        = 
```

`Windows Shortcut`
```
Target: C:\ffxi\Ashita-v4beta\Ashita-cli.exe localhost_1.ini
Start in: C:\ffxi\Ashita-v4beta\
```

You don't need to try and be lightning fast and try to get screenshots of things, I asked if there was anything interesting in the logs - which exist in the Ashita/logs folder.

**Comment by Manpigg** [comment]
> I can't vouch for whatever instructional videos exist elsewhere, but I'm 99% sure the LSB guides are all up to date.
> 
> I'm not sure if the arguments in the ini (that are directly passed to xiloader) are case-sensitive or not, be careful about that. https://github.com/LandSandBoat/xiloader/blob/main/src/main.cpp#L365
> 
> Here's a breakdown of exactly my local setup, where I double click my shortcut and it launches the client (if the account doesn't exist because I've wiped my db it'll catch on the main xiloader screen and I can create the account at that point):
> 
> ```
> Replaced C:\ffxi\Ashita-v4beta\bootloader\pol.exe with the newest xiloader, and renamed to pol.exe
> ```
> 
> `C:\ffxi\Ashita-v4beta\config\boot\localhost_1.ini`
> 
> ```
> [ashita.boot]
> ; Private Server Usage
> file        = .\\bootloader\\pol.exe
> command     = --server 127.0.0.1 --user admin1 --pass admin1
> gamemodule  = ffximain.dll
> script      = default.txt
> args        = 
> ```
> 
> `Windows Shortcut`
> 
> ```
> Target: C:\ffxi\Ashita-v4beta\Ashita-cli.exe localhost_1.ini
> Start in: C:\ffxi\Ashita-v4beta\
> ```
> 
> You don't need to try and be lightning fast and try to get screenshots of things, I asked if there was anything interesting in the logs - which exist in the Ashita/logs folder.

Ok,  thank you,  i will look into these things here you mentioned.  Appreciate your time.
